default: &default
  host: 'http://localhost:9200/'

docker: &docker
  host: 'http://elasticsearch:9200'

test:
  <<: *docker

development:
  <<: *docker

staging:
  <<: *default

production:
  <<: *default
